config/routes.rb
Rails.application.routes.draw do
  get '/books/new', to: 'books#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to =>"homes#top"
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  # .../books/1 や .../books/3 に該当する
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book' 
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
    # トップページのアクション
  end

  def start
    # startページのアクション
    redirect_to root_path  # 例：トップページにリダイレクト
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "successfully" 
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      flash[:notice] = "error"
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id]) 
  end

  def edit
    @book = Book.find(params[:id]) 
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(book.id)  
    else
      @book = Book.find(params[:id]) 
      flash[:notice] = "error"
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト 
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
<div>
  <label>Title</label><br>
  <%= f.text_field :title %>
</div>
<div>  
  <label>Body</label><br>
  <%= f.text_area :body %>
</div>

  <div><%= f.submit 'Update Book' %></div>

  <div><%= link_to 'Show', book_path(@book.id) %>
      |
   <%= link_to 'Back', books_path %>
  </div>
  
  
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>
<table class='table table-hover table-inverse'>
<thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
<tr>
  <td><%= book.title %></td>
  <td><%= book.body %></td>
  <td><%= link_to 'Show', book_path(book) %></td>
  <td><%= link_to 'Edit', edit_book_path(book) %></td>
  <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
</td>
  </tr>
  <% end %>
  </tbody>
  </table>

  <h1>New book</h1>
  <% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<!-- form_with部分 -->
<%= form_with model: Book.new do |f| %>
  
  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Body</h4>
  <%= f.text_area :body %><br>
	
  <%= f.submit 'Create Book' %>

<% end %>

app/views/books/new.html.erb
<h1>New book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>nTitle can't be blank Body can't be blank\nTitle\nBody"
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<!-- form_with部分 -->
<%= form_with model: Book.new do |f| %>
  
  <h4>title</h4>
  <%= f.text_field :title %>
	
  <h4>body</h4>

  <%= f.text_area :body %>
	<div>
  <%= f.submit 'Create Book' %>
  </div>
<% end %>

app/views/books/show.html.erb
<html>
  <head>
    <link rel="stylesheet" media="all" href="/assets/application-d12397cbc3a266ce5a99f7b588223090c55ca04a439953bb5f9304395de93fc3.css" data-turbolinks-track="reload">
    <script src="/assets/application-114264dd93c8ff30e4335b71eed7949d66c4e7a8eb62e2de6284c046fe07104b.js" data-turbolinks-track="reload"></script>
    <title>WebCampBackendNew</title>
    <meta name="csrf-param" content="authenticity_token">
    <meta name="csrf-token" content="GEYlTWByDflJUl21O95svHTwbdtCZSKk+n5EkpTIkgk5InTydkcjJH5flr2nCyvK6atDUC8Tj/+2CeUJ4266yg==">
  </head>

  <h2>Title</h2>
<p><%= @book.title %></p>

  <h2>Body</h2>
<p><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %>
      |
    <a class="back" href="/books">Back</a>
    <body>
    <p id="notice"></p>
    </body>
</html>

app/views/homes/top.html.erb
<html>
  <head>
   <link rel="stylesheet" media="all" href="/assets/application-d12397cbc3a266ce5a99f7b588223090c55ca04a439953bb5f9304395de93fc3.css" data-turbolinks-track="reload">
   <script src="/assets/application-114264dd93c8ff30e4335b71eed7949d66c4e7a8eb62e2de6284c046fe07104b.js" data-turbolinks-track="reload"></script>
   <title>WebCampBackendNew</title>
   <meta name="csrf-param" content="authenticity_token">
   <meta name="csrf-token" content="vKa7jfhHDYtztgneRYvFcteBezDfvvltA/d//+MLfxrXSSFDZcsYGqYnl/P1Fw7ASmbNc74DZGal+w8J0T021Q==">
  <head>
  
<body>
  <h1>
   ようこそ
   <strong>Bookers</strong> 
   へ !
 </h1>
 <p>
 <strong>Bookers</strong>
 では、さまざまな書籍に関するあなたの意見や
 </p>
    <p>印象を共有し交換することができます</p>
    <p>
    <%= link_to 'Start', books_path %>
    </p>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>